language: r

r_packages: 
  - caretEnsemble
  - testthat
  - party
  - pROC
  - e1071
  - mvtnorm
  - ggplot2
  - rpart
  - modeltools

notifications:
  email:
    on_success: change
    on_failure: change
